### ISSUE TITLE
Script fails: returned non-zero exit status 1

### ISSUE THREAD

**Issue by maxbec** [sjafferali/paperless-titles-from-ai#15]
Hey,

i get this error on post-consume (The *** are only for more privacy):

```
Command '['/usr/src/paperless/scripts/app/main.py', '140', '***_NTF_1.1.4.pdf', '/usr/src/paperless/media/documents/originals/***/***/***/***_Posteingang_03.pdf', '/usr/src/paperless/media/documents/thumbnails/0000140.webp', '/api/documents/140/download/', '/api/documents/140/thumb/', '***', 'Posteingang']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "/usr/local/lib/python3.12/site-packages/celery/app/trace.py", line 453, in trace_task

    R = retval = fun(*args, **kwargs)

                 ^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/site-packages/celery/app/trace.py", line 736, in __protected_call__

    return self.run(*args, **kwargs)

           ^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.12/site-packages/asgiref/sync.py", line 327, in main_wrap

    raise exc_info[1]

  File "/usr/src/paperless/src/documents/tasks.py", line 148, in consume_file

    msg = plugin.run()

          ^^^^^^^^^^^^

  File "/usr/src/paperless/src/documents/consumer.py", line 632, in run

    self.run_post_consume_script(document)

  File "/usr/src/paperless/src/documents/consumer.py", line 344, in run_post_consume_script

    self._fail(

  File "/usr/src/paperless/src/documents/consumer.py", line 151, in _fail

    raise ConsumerError(f"{self.filename}: {log_message or message}") from exception
    ```
    
    Any ideas what i am doing wrong here?

**Comment by sjafferali** [comment]
It seems like the post consume script errored out, although, the cause isn't evident from the log snippet you provided. Could you provide the full logs from that post consume task? I would expect the lines before the above traceback to be more useful. Feel free to redact anything you need.

Alternatively, you can also try running the below command that failed manually from inside the docker container. 
```
/usr/src/paperless/scripts/app/main.py 140 ***_NTF_1.1.4.pdf /usr/src/paperless/media/documents/originals/***/***/***/***_Posteingang_03.pdf /usr/src/paperless/media/documents/thumbnails/0000140.webp /api/documents/140/download/ /api/documents/140/thumb/ *** Posteingang
```

**Comment by maxbec** [comment]
I get this error:
```
11/05/2024 05:22:11 PM ERROR Missing DOCUMENT_ID
```
I think the call does not work with just putting the first argument as document id there:
```
main.py 180
```

I tried this one, which is working:
```
export DOCUMENT_ID=181 && /usr/src/paperless/scripts/app/main.py
```

Maybe you should clarify this in the README.

**Comment by maxbec** [comment]
main.py is expecting the document id as env:

```python
if __name__ == '__main__':
    LOGLEVEL = os.environ.get('LOGLEVEL', 'INFO').upper()
    logging.basicConfig(format='%(asctime)s %(levelname)s %(message)s',
                        datefmt='%m/%d/%Y %I:%M:%S %p',
                        level=LOGLEVEL)
    DRY_RUN = strtobool(os.getenv("DRY_RUN", "false"))
    if DRY_RUN:
        logging.info("DRY_RUN ENABLED")
    run_for_document(os.getenv("DOCUMENT_ID"))

**Comment by sjafferali** [comment]
@maxbec According to the [paperless-ngx docs](https://docs.paperless-ngx.com/advanced_usage/#post-consume-script), the script is executed with these arguments as environment variables when the post-consume script runs. 

If this worked after you exported the environment variable and executed it manually, I am curious what your initial failure was when paperless tried to execute it. It should not have been the same error as paperless would have executed the script with the correct environment variable set.

Are the failures with the script running in the post-consume context still occurring for you? If it is, you may be able to find the full traceback in the logs section.

**Comment by maxbec** [comment]
I now have the problem that it cannot find openai...

```
[2024-11-05 19:46:10,286] [WARNING] [paperless.consumer]   File "/usr/src/paperless/scripts/app/main.py", line 9, in <module>
[2024-11-05 19:46:10,286] [WARNING] [paperless.consumer]     from openai import OpenAI
[2024-11-05 19:46:10,287] [WARNING] [paperless.consumer] ModuleNotFoundError: No module named 'openai'
```

I think there is a problem with my init file. But i dont know why. Here are the rights
`-rwx------  1 root root  41 Aug 17 02:41 openai.sh`

**Comment by sjafferali** [comment]
@maxbec Try changing the permissions for both `openai.sh` and the `init` directory that the file is in to 755. That should work regardless of what user is executing it. That is also the permissions on my installation. 

If it works, let me know and I will add a note about it in the documentation in case others run into this.

**Comment by maxbec** [comment]
You are the man. It worked! Thank you.
