### ISSUE TITLE
Wrong path to .env file

### ISSUE THREAD

**Issue by grostim** [sjafferali/paperless-titles-from-ai#5]
I am refering to this line in your code:
https://github.com/sjafferali/paperless-titles-from-ai/blob/be49e58f51fe6aaf7bad4363351facd8102a8bb2/app/cfg.py#L6C2-L6C79

I think that if the volumes are set as suggested in your readme.md, then the .env file path should be: /usr/src/paperless/scripts/.env

**Comment by sjafferali** [comment]
Thanks @grostim . I have fixed this path in https://github.com/sjafferali/paperless-titles-from-ai/pull/6 .
