### ISSUE TITLE
Backfill only fetches first page; file permissions

### ISSUE THREAD

**Issue by yaakovfeldman** [sjafferali/paperless-titles-from-ai#8]
Thanks for the script, it is useful.

A couple of notes:

- The init folder (used to ensure openai package is installed) must be owned by root or will not be run
- My 300 documents used about 900k tokens. `GPT-3.5-turbo-0125` ($0.50 / 1m tokens) was perfectly adequate and a tenth of the price of `GPT-4o-2024-05-13`
- The backfill script fetches /api/documents/ https://github.com/sjafferali/paperless-titles-from-ai/blob/e4ede1c54aa41268eb668f28a1de1207f97807e6/app/cli.py#L12 but this is a paginated api and will only return the first 35 or so results. Personally, I wanted to only overwrite default titles (those starting 'Scan') so I tweaked the script to point to `/api/documents/?query=title__icontains=Scan` (which returns all items with 'Scan' in the title) and then simply ran it a few times until it stopped finding files. But a proper fix would require iterating over all pages

**Comment by sjafferali** [comment]
@yaakovfeldman Thanks for finding this and posting these details. I have updated the backfill script to support actually fetching all documents by looping multiple requests when multiple pages are returned. 

I also added some additional notes regarding the permissions and openai model costs in the README.md file. https://github.com/sjafferali/paperless-titles-from-ai/issues/8 .
